### ISSUE TITLE
s32g399ardb3 make fails

### ISSUE THREAD

**Issue by balupamidipati** [nxp-auto-linux/u-boot#3]
Could not find zonf.tab.c file
sudo make s32g399ardb3_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
/bin/sh: 1: bison: not found
make[1]: *** [scripts/Makefile.lib:226: scripts/kconfig/zconf.tab.c] Error 127
make: *** [Makefile:539: s32g399ardb3_defconfig] Error 2

Is there any alternative file that can be replace this ?

**Comment by catalinudmanxp** [comment]
Please see the error: "/bin/sh: 1: bison: not found"
flex and bison are dependencies required for building (upstream) U-Boot. See also chapter 3.2.2 Setting up and building U-Boot bootloader from Linux BSP User Manual

**Comment by catalinudmanxp** [comment]
Works as expected when building upstream U-Boot.

**Comment by balupamidipati** [comment]
Thanks . It is working now.
